//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DnDApp2.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DnDApp2.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;DocumentElement&gt;
        ///  &lt;ancestry&gt;
        ///    &lt;name&gt;Bugbear&lt;/name&gt;
        ///    &lt;attack&gt;2&lt;/attack&gt;
        ///    &lt;power&gt;0&lt;/power&gt;
        ///    &lt;defense&gt;0&lt;/defense&gt;
        ///    &lt;toughness&gt;0&lt;/toughness&gt;
        ///    &lt;morale&gt;1&lt;/morale&gt;
        ///    &lt;traits&gt;Martial&lt;/traits&gt;
        ///    &lt;traitsCost&gt;100&lt;/traitsCost&gt;
        ///  &lt;/ancestry&gt;
        ///  &lt;ancestry&gt;
        ///    &lt;name&gt;Dragonborn&lt;/name&gt;
        ///    &lt;attack&gt;2&lt;/attack&gt;
        ///    &lt;power&gt;2&lt;/power&gt;
        ///    &lt;defense&gt;1&lt;/defense&gt;
        ///    &lt;toughness&gt;1&lt;/toughness&gt;
        ///    &lt;morale&gt;1&lt;/morale&gt;
        ///    &lt;traits&gt;Courageous&lt;/traits&gt;
        ///    &lt;t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ancestories_saf {
            get {
                return ResourceManager.GetString("ancestories_saf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;DocumentElement&gt;
        ///  &lt;equipment&gt;
        ///    &lt;name&gt;Light&lt;/name&gt;
        ///    &lt;attack&gt;0&lt;/attack&gt;
        ///    &lt;power&gt;1&lt;/power&gt;
        ///    &lt;defense&gt;1&lt;/defense&gt;
        ///    &lt;toughness&gt;0&lt;/toughness&gt;
        ///    &lt;morale&gt;0&lt;/morale&gt;
        ///  &lt;/equipment&gt;
        ///  &lt;equipment&gt;
        ///    &lt;name&gt;Medium&lt;/name&gt;
        ///    &lt;attack&gt;0&lt;/attack&gt;
        ///    &lt;power&gt;2&lt;/power&gt;
        ///    &lt;defense&gt;2&lt;/defense&gt;
        ///    &lt;toughness&gt;0&lt;/toughness&gt;
        ///    &lt;morale&gt;0&lt;/morale&gt;
        ///  &lt;/equipment&gt;
        ///  &lt;equipment&gt;
        ///    &lt;name&gt;Heavy&lt;/name&gt;
        ///    &lt;attack&gt;0&lt;/attack&gt;
        ///    &lt;power&gt;4&lt;/power&gt;
        ///    &lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string equipment_saf {
            get {
                return ResourceManager.GetString("equipment_saf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;DocumentElement&gt;
        ///  &lt;experience&gt;
        ///    &lt;name&gt;Green&lt;/name&gt;
        ///    &lt;attack&gt;0&lt;/attack&gt;
        ///    &lt;power&gt;0&lt;/power&gt;
        ///    &lt;defense&gt;0&lt;/defense&gt;
        ///    &lt;toughness&gt;0&lt;/toughness&gt;
        ///    &lt;morale&gt;0&lt;/morale&gt;
        ///  &lt;/experience&gt;
        ///  &lt;experience&gt;
        ///    &lt;name&gt;Regular&lt;/name&gt;
        ///    &lt;attack&gt;1&lt;/attack&gt;
        ///    &lt;power&gt;0&lt;/power&gt;
        ///    &lt;defense&gt;0&lt;/defense&gt;
        ///    &lt;toughness&gt;1&lt;/toughness&gt;
        ///    &lt;morale&gt;1&lt;/morale&gt;
        ///  &lt;/experience&gt;
        ///  &lt;experience&gt;
        ///    &lt;name&gt;Seasoned&lt;/name&gt;
        ///    &lt;attack&gt;1&lt;/attack&gt;
        ///    &lt;power&gt;0&lt;/powe [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string experiences_saf {
            get {
                return ResourceManager.GetString("experiences_saf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;DocumentElement&gt;
        ///  &lt;size&gt;
        ///    &lt;size&gt;1d4&lt;/size&gt;
        ///    &lt;costmod&gt;66&lt;/costmod&gt;
        ///  &lt;/size&gt;
        ///  &lt;size&gt;
        ///    &lt;size&gt;1d6&lt;/size&gt;
        ///    &lt;costmod&gt;100&lt;/costmod&gt;
        ///  &lt;/size&gt;
        ///  &lt;size&gt;
        ///    &lt;size&gt;1d8&lt;/size&gt;
        ///    &lt;costmod&gt;133&lt;/costmod&gt;
        ///  &lt;/size&gt;
        ///  &lt;size&gt;
        ///    &lt;size&gt;1d10&lt;/size&gt;
        ///    &lt;costmod&gt;166&lt;/costmod&gt;
        ///  &lt;/size&gt;
        ///  &lt;size&gt;
        ///    &lt;size&gt;1d12&lt;/size&gt;
        ///    &lt;costmod&gt;200&lt;/costmod&gt;
        ///  &lt;/size&gt;
        ///&lt;/DocumentElement&gt;.
        /// </summary>
        internal static string sizes_saf {
            get {
                return ResourceManager.GetString("sizes_saf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;DocumentElement&gt;
        ///  &lt;trait&gt;
        ///    &lt;name&gt;Amphibious&lt;/name&gt;
        ///    &lt;desc&gt;This unit does not suffer terrain penalties for fighting in water or on land. &lt;/desc&gt;
        ///    &lt;cost&gt;50&lt;/cost&gt;
        ///  &lt;/trait&gt;
        ///  &lt;trait&gt;
        ///    &lt;name&gt;Bred for war&lt;/name&gt;
        ///    &lt;desc&gt;This unit cannot be diminished, and cannot have disadvantage on morale checks. &lt;/desc&gt;
        ///    &lt;cost&gt;100&lt;/cost&gt;
        ///  &lt;/trait&gt;
        ///  &lt;trait&gt;
        ///    &lt;name&gt;Brutal&lt;/name&gt;
        ///    &lt;desc&gt;This unit inflicts two casualties on a successful power test.
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string traits_saf {
            get {
                return ResourceManager.GetString("traits_saf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;DocumentElement&gt;
        ///  &lt;type&gt;
        ///    &lt;name&gt;Airborne&lt;/name&gt;
        ///    &lt;attack&gt;0&lt;/attack&gt;
        ///    &lt;power&gt;0&lt;/power&gt;
        ///    &lt;defense&gt;0&lt;/defense&gt;
        ///    &lt;toughness&gt;0&lt;/toughness&gt;
        ///    &lt;morale&gt;3&lt;/morale&gt;
        ///    &lt;costmod&gt;200&lt;/costmod&gt;
        ///  &lt;/type&gt;
        ///  &lt;type&gt;
        ///    &lt;name&gt;Archers&lt;/name&gt;
        ///    &lt;attack&gt;0&lt;/attack&gt;
        ///    &lt;power&gt;1&lt;/power&gt;
        ///    &lt;defense&gt;0&lt;/defense&gt;
        ///    &lt;toughness&gt;0&lt;/toughness&gt;
        ///    &lt;morale&gt;1&lt;/morale&gt;
        ///    &lt;costmod&gt;175&lt;/costmod&gt;
        ///  &lt;/type&gt;
        ///  &lt;type&gt;
        ///    &lt;name&gt;Cavalry&lt;/name&gt;
        ///    &lt;attack&gt;1&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string types_saf {
            get {
                return ResourceManager.GetString("types_saf", resourceCulture);
            }
        }
    }
}
